### ISSUE TITLE
CAMS CAS Parsing support for Dividend payout transaction 

### ISSUE THREAD

**Issue by SudhirSNaik** [codereverser/casparser#10]
Hi,

CAMS CAS has Dividend Payout transactions like below. 

![CAMS_CAS1](https://user-images.githubusercontent.com/73683130/102934289-d655e200-44c9-11eb-80a3-30a328610160.JPG)

TRANSACTION_RE doesn't match since "units", "nav" and "balance" columns are missing in these entries.

Can the parser be updated to handle the Dividend Payout transaction? Not sure if Karvy CAS has similar format.
Also, the Dividend amount may need to be negated for XIRR calculations.

**Comment by codereverser** [comment]
Many thanks! shall upload a fix for testing.

**Comment by codereverser** [comment]
Updated `TRANSACTION_RE` in #12 to parse dividend transactions. This should work hopefully.

**Comment by SudhirSNaik** [comment]
Works well.. 
Dividend Payout and STT Paid transaction are picked up now... Thank you.

Can another flag be added for Dividend Reinvestment for transactions like below (is_dividend_reinvestment).

![image](https://user-images.githubusercontent.com/73683130/103051877-cd463d00-45bd-11eb-8f87-253374ed687b.png)

I seem to have all sorts of transactions from earlier days!!! :)

**Comment by codereverser** [comment]
Many thanks. These are really helpful. really difficult to come across use cases that cover all these scenarios. shall update the branch soon. 

I have already been planning for adding a transaction type enum in the json with values `PURCHASE`, `REDEMPTION`, `DIVIDEND_PAYOUT`, `DIVIDEND_REINVEST`, `TAX`/`STT`, `MISC` but was not sure if these would cover all use cases.

**Comment by codereverser** [comment]
Added commits to the branch `fix/dividends` to flag dividend reinvestments. Also added `dividend_rate` property in case of  dividend transactions. 

Please let me know if this works fine for your files.

**Comment by SudhirSNaik** [comment]
Code working fine... Everything being parsed as expected.

"I have already been planning for adding a transaction type enum in the json with values PURCHASE, REDEMPTION, DIVIDEND_PAYOUT, DIVIDEND_REINVEST, TAX/STT, MISC but was not sure if these would cover all use cases."
       --> This will be very helpful in further analysis of parsed date.

**Comment by codereverser** [comment]
Many thanks for testing the code. It is really appreciated. 

I'll add transaction type detection in the next version. just needs to finalise the different types of transactions possible and the classification logic.

**Comment by SudhirSNaik** [comment]
> 
> I have already been planning for adding a transaction type enum in the json with values `PURCHASE`, `REDEMPTION`, `DIVIDEND_PAYOUT`, `DIVIDEND_REINVEST`, `TAX`/`STT`, `MISC` but was not sure if these would cover all use cases.

Below are additional categories I can think of
`SIP_PURCHASE`, `SWITCH_REDEMPTION`, `SWITCH_PURCHASE`, `MERGER_REDEMPTION`, `MERGER_PURCHASE`
