### ISSUE TITLE
Wrong amfi code returned

### ISSUE THREAD

**Issue by yogesh-ds** [codereverser/casparser#101]
casparser returns 119893 for BARODA BNP PARIBAS LARGE CAP FUND - DIRECT GROWTH GROWTH for which ISIN is INF251K01HN7. AMFI site has 150187 listed as amfi code for this scheme.

**Comment by yogesh-ds** [comment]
Here's the code snippet that is getting me incorrect amfi number, screenshot of csv data that the code generates and CAS snapshot minus personal info.
I don't feel like it is an issue with the CAS structure. Probably the reference data you source this information from seems to be out of date or not in sync with AMFI official data?

    datacsv = casparser.read_cas_pdf(filepath, password,output="csv")
    string_data = StringIO(datacsv)
    data=pd.read_csv(string_data)
    data.to_csv(data_path+"rawCASdata.csv")
![amfi-issue](https://github.com/user-attachments/assets/975fd493-b699-43bb-914d-cbd0d99ba47c)
![CAS_Screenshot](https://github.com/user-attachments/assets/121afe25-26b5-4103-ae3d-206afeb20a5e)

**Comment by codereverser** [comment]
yeah. you are right.. 
the isin.db has multiple data for ISIN INF251K01HN7
- 150187 (current fund)
- 119893 (old AMFI code before merger of Baroda AMC with BNP Paribas ref: https://www.amfiindia.com/spages/NAVAll_31Jan2018.txt?t=04122024051132) 

I'll push a fix soon, so that the library returns the correct AMFI code in such cases.

**Comment by codereverser** [comment]
can you please try testing after updating the dependency package to latest version? 

```
pip install casparser-isin==2024.12.5
```

**Comment by yogesh-ds** [comment]
Tested with the updated dependency package. Worked fine. Thanks!
