### ISSUE TITLE
CLI works fine but I can't call read_cas_pdf in code

### ISSUE THREAD

**Issue by nirmanp6** [codereverser/casparser#11]
I am trying to use your library. Followed all steps as listed on your pypi page. But it always shows the error
module casparser has no attribute.
`
data = casparser.read_cas_pdf('/home/path.pdf', 'pwd')
AttributeError: module 'casparser' has no attribute 'read_cas_pdf'
`

Code:
`
import casparser
data = casparser.read_cas_pdf('/home/path.pdf', 'pwd')
`

Great work regardless thank you.

**Comment by nirmanp6** [comment]
Sorry I figured it out, code works great. Keep up the good work!

**Comment by codereverser** [comment]
Thanks! just curious, was it due to any issue with the code? (or is there any need to update the documentation to avoid such errors)

**Comment by nirmanp6** [comment]
No it wasn't due to your code at all. I used your function read_cas_pdf from a file that was named casparser(stupid move, naming the file same as the library name). So it was giving me the error casparser has no attribute read_cas_pdf.
