### ISSUE TITLE
[CAMS CAS]Issue in folio parsing when PAN data unavailable

### ISSUE THREAD

**Issue by SudhirSNaik** [codereverser/casparser#14]
Hi,

Folio is not getting parsed in below case. Transactions are getting mapped to previously parsed folio.
![image](https://user-images.githubusercontent.com/73683130/103168537-fe429e00-4859-11eb-8ce2-383aa13f364d.png)

Below are details of pdf elements and lines for debug

`[28.93000030517578, 93.44519805908203, 553.7244873046875, 103.9654769897461, 'Date\t\tTransaction\t\tAmount\t\tUnits\t\tPrice\t\tUnit']` 
`[358.6300048828125, 102.31519317626953, 566.5147705078125, 124.0643310546875, '(INR)\t\t(INR)\t\tBalance\nKYC: OK']`   
`[28.93000030517578, 113.60517120361328, 99.20275115966797, 124.12545013427734, 'Folio No: 99999999']`

`'Date\t\tTransaction\t\tAmount\t\tUnits\t\tPrice\t\tUnit'`
`'Folio No: 99999999\t\t(INR)\t\t(INR)\t\tBalance\nKYC: OK'`

**Comment by codereverser** [comment]
Oh. Looks like PANKYC field is missing for this portfolio. shall fix this soon.

**Comment by SudhirSNaik** [comment]
The issue is partially fixed. 

Working:
Folios are parsed separately and transactions are mapped to corresponding folios properly

Not working:
Actual Folio number has additional data attached
`'folio' = '99999999\t\t(INR)\t\t(INR)\t\tBalance'`


You can check the `elements` and `lines` in my previous comment. The Folio No: line has data from above row as well.

**Comment by codereverser** [comment]
this seems tricky. Let me work on it. 

btw are you using pdfminer or pymupdf backend?

**Comment by SudhirSNaik** [comment]
> btw are you using pdfminer or pymupdf backend?

pymupdf
