### ISSUE TITLE
Parsed closing units not the same as calc_close

### ISSUE THREAD

**Issue by nirmanp6** [codereverser/casparser#16]
So, I have a unique problem. My CAS has two discreet entries for the same folio number, due to switch from regular plan to direct plan. The Switch in is listed before the Switch out. So what ends up happening is the program parses the closing unit balance of 7.350 first and closing unit balance of 0.00 from the next entry overwrites it. So the parsed closing unit balance is 0.00 and the calc_close is 7.350. Which ends up as an error in the CLI version, but raises no error in the normal call. I saw your TODO comment about adding this validation as well. So here's something you can test it against.

If you don't mind me suggesting options, you could maybe add them up instead of replacing, or include calc_close in the dict too.

Also, here is the parsed data of the pdf for your convenience:

`'Folio No: 0000000 / 00\t\tPAN: XXXXX0000X\t\tKYC: OK  PAN: OK', 'GD65-IDFC Low Duration Fund-Growth-(Direct Plan) (Advisor: INA000000000)\t\tRegistrar : CAMS', 'Opening Unit Balance: 0.000', '14-Aug-2019\t\tNORMAL SWITCH - From IDFC Low Duration Fund-Gr-(Reg Pln)-BSE -\t\t202.98\t\t7.350\t\t27.6156\t\t7.350', 'Closing Unit Balance: 7.350\t\tNAV on 22-Dec-2020: INR 30.3779\t\tValuation on 22-Dec-2020: INR 223.28', '"Entry Load: Nil - Exit Load : Nil  W.E.F 29/June/2012 . Please refer the Offer Document / Addendum issued from time to time"', 'Folio No: 0000000 / 00\t\tPAN: XXXX0000X\t\tKYC: OK  PAN: OK', 'G65-IDFC Low Duration Fund-Growth-(Regular Plan) (Advisor: ARN-000000)\t\tRegistrar : CAMS', 'Opening Unit Balance: 0.000', '18-Jun-2019\t\tPurchase\t\t200.00\t\t7.424\t\t26.9379\t\t7.424', '19-Jun-2019 ***Address Updated from KRA Data***', '19-Jun-2019 ***Registration of Nominee***', '14-Aug-2019\t\tSwitch Out  - To IDFC Low Duration Fund-Gr-(Dir Pln)-BSE -\t\t(202.98)\t\t(7.424)\t\t27.3406\t\t0.000', '30-Sep-2020 ***Address Updated from KRA Data***', 'Closing Unit Balance: 0.000\t\tNAV on 22-Dec-2020: INR 29.9852\t\tValuation on 22-Dec-2020: INR 0.00', '"Entry Load: Nil - Exit Load : Nil  W.E.F 29/June/2012 . Please refer the Offer Document / Addendum issued from time to time"
`

I have attached relevant screen shots of all, below:
![CAS-SCAN](https://user-images.githubusercontent.com/47811723/103408982-bfc71f00-4b8a-11eb-9505-adb91676b8f8.jpg)
![CLI-ERROR-SS](https://user-images.githubusercontent.com/47811723/103408986-c0f84c00-4b8a-11eb-897c-41c944d59ecf.jpg)
![CLI-SS](https://user-images.githubusercontent.com/47811723/103409196-9d81d100-4b8b-11eb-9b89-09a337d0fcb0.jpg)
![RESULT-DICT](https://user-images.githubusercontent.com/47811723/103409197-9e1a6780-4b8b-11eb-9cc2-dbaca827e6fd.jpg)

**Comment by codereverser** [comment]
Many thanks for the detailed bug report. I'll investigate it and get back to you soon. 

The second screenshot seems to be from an older version of the package. Also the bug where the schemes with brackets in names were not being parsed properly,  has been fixed recently. Can you please try the code after updating it to the latest version? 

```bash
pip install 'casparser[mupdf]==0.3.8'
```

**Comment by nirmanp6** [comment]
I'm having some problems updating to the latest version, due to MuPdf. I couldn't find a solution to this on the internet. The installation gives the following error:

` error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for PyMuPDF `

**Comment by codereverser** [comment]
Can you please send me screenshots of the error? Also details on the OS/python version used.. 

You can also use casparser without mupdf by 

```bash
pip install -U casparser
```
which will use `pdfminer` for parsing [It is a bit slower than mupdf, but usage/results would be same]

**Comment by nirmanp6** [comment]
Thanks i managed to update it to the latest version. It works stable now and the error i use to face before has gone away.

**Comment by nirmanp6** [comment]
I have a question, do you have any plans for adding an id field to transaction? Something like an auto-generated id for every transaction using some logic that concatenates two fields(folio and date) and a counter to compute a unique id?

**Comment by codereverser** [comment]
Nice to know that, you have managed to solve the issue. 

re: adding unique id to transaction, I guess it may be out of scope of the casparser library as such. Moreover there are CAS statements with same details for folio number, transaction date & description (see pic below), and for such rows, generating a consistent unique id would be difficult from the library. 

![image](https://user-images.githubusercontent.com/8553055/104017871-e74b6680-51de-11eb-9523-3ef529529d0e.png)

I feel it may be best to leave it to the user to generate unique ids depending on the application.
