### ISSUE TITLE
Print the Valuation of the Fund as well

### ISSUE THREAD

**Issue by mandys** [codereverser/casparser#2]
Thank you for a great parser.

Took me a few tries to understand which report the parser will pick up as Cams is offering many ( so confusing! :-)

Finally, it worked for me.

The table printed is great.
But, what as a user I would also like to see is the total valuation of my fund.

This is only giving the Open/Close rates but the cams file also has:
Valuation on 06-Nov-2020 INR XX,XXX.XX

Can we pick that up too ?

Thanks.

**Comment by codereverser** [comment]
Sure! :) 
the latest version (v0.3.4) include individual scheme valuation in the library as well as cli output. Can you please give it a try?

**Comment by mandys** [comment]
Tested and works like a charm!

Thank you for the quick response and taking out time over a weekend to get this in 👍
