### ISSUE TITLE
Unable to parse scheme name when 'Registrar' is on a different line

### ISSUE THREAD

**Issue by sandeshgoel** [codereverser/casparser#22]
I have a CAS statement in with 'Registrar' is shown on a separate line before the scheme name (since scheme name is slightly long). This results in failure to parse the scheme name. See attached snapshot

![image](https://user-images.githubusercontent.com/47023927/105450269-1dd5b680-5ca0-11eb-9a60-6c829ad98bdf.png)

**Comment by codereverser** [comment]
This is a bit tricky as it seems the registrar is appearing one line above the scheme. I have sample CAS files with multi-line schemes, but in all of them the registrar is in the same line as the scheme; like,

![image](https://user-images.githubusercontent.com/8553055/105456751-b6bdff00-5cab-11eb-8e30-de67ecaaa02b.png)

**Comment by codereverser** [comment]
Would you mind sharing one example file with me for debugging? This is a new format of scheme layout that is not yet handled by the parser and may require tweaking the pdf parsing parameters. File without any transaction history is also fine as long as the scheme names are present. 

If not possible, that's fine. I'll see if it is possible to arrange one from my acquaintances. 

Email: codereverser .at. gmail

**Comment by sandeshgoel** [comment]
let me try to get an example file for you

**Comment by codereverser** [comment]
fixed in 32878e06c239474562689b1ed8f38545184f2c57 (v0.4.2)
