### ISSUE TITLE
Unable to parse negative unit balance

### ISSUE THREAD

**Issue by sandeshgoel** [codereverser/casparser#23]
There seems to be an assumption that unit balance is never negative. While this assumption seems reasonable, I have a statement in which unit balance is shown as negative (some slight rounding error by AMC). This causes parsing to fail. I believe the fix is simply applying the same logic to unit balance as is applied to units.

See screenshot below for example where it fails.
![image](https://user-images.githubusercontent.com/47023927/105450637-eadff280-5ca0-11eb-83d0-022b9a0b7d9b.png)

**Comment by codereverser** [comment]
This should be fixed in ef36eb56f74508b5f79e93151a9e52fc36d4caa6 in master branch. Please re-open if doesn't solve the issue. 

I'll soon make the next release in pypi after fixing the other pending bugs.
