### ISSUE TITLE
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>] exception when parsing IDCW payout transaction

### ISSUE THREAD

**Issue by sathishweb** [codereverser/casparser#29]
Thanks for your script. It is very useful. I am trying to build some automation on top of this to analyze my MF investments. 
Got this exception when parsing the amount of an IDCW payout transaction. Let me know if I can collect any more debug info to help. I will also see if I can debug further.
#### Versions used
casparser==0.4.6
python 3.8.3

### Traceback
  File "C:\Sathish\python\mf_statement_parser\venv2\lib\site-packages\casparser\parsers\__init__.py", line 35, in read_cas_pdf
    processed_data = process_cas_text("\u2029".join(partial_cas_data.lines))
  File "C:\Sathish\python\mf_statement_parser\venv2\lib\site-packages\casparser\process\__init__.py", line 28, in process_cas_text
    return process_detailed_text(text)
  File "C:\Sathish\python\mf_statement_parser\venv2\lib\site-packages\casparser\process\cas_detailed.py", line 167, in process_detailed_text
    amt = Decimal(m.group(3).replace(",", "_").replace("(", "-"))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

### Screenshot of the transaction causing the issue

I ran in debug mode and noticed that it fails when attempting to parse the following transaction in pdf

![image](https://user-images.githubusercontent.com/28622838/118349528-d46ee700-b56e-11eb-8b5e-7622e51b570d.png)

### pyCharm debug screenshot

![image](https://user-images.githubusercontent.com/28622838/118349410-2105f280-b56e-11eb-9781-1df6a7d96d8a.png)

### Some more debug info
I got into the console on the debugger and found that we have a "." in the m.group(3) instead of probably the "amount" number?

m.group(3)
'.'

m.group(3).replace(",", "_").replace("(", "-")
'.'

amt = Decimal(m.group(3).replace(",", "_").replace("(", "-"))

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.5\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 1, in Exec
    def Exec(exp, global_vars, local_vars=None):
  File "<input>", line 1, in <module>
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

**Comment by sathishweb** [comment]
To add, I did not face this issue with an old CAS report which I generated in 2020. It is failing only with the latest report that I generated today.

**Comment by sathishweb** [comment]
Some more debug info. I get into the console on the debugger and found that we have a "." in the m.group(3) instead of probably the "amount" number?

m.group(3)
'.'

m.group(3).replace(",", "_").replace("(", "-")
'.'

amt = Decimal(m.group(3).replace(",", "_").replace("(", "-"))

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.5\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 1, in Exec
    def Exec(exp, global_vars, local_vars=None):
  File "<input>", line 1, in <module>
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

**Comment by codereverser** [comment]
Can you please let me know the value of the following variables just before the crash? 
```python
print([line, m.groups()])
```

Looks like some issue with while parsing multi-line descriptions..

**Comment by sathishweb** [comment]
#### line
'12-Mar-2021\t\t***IDCW Payout @ Rs.4.50000000 per unit  (TDS :453.13, TDS Rate:\t\t.\t\t50%)***\t\t5,588.54'

#### m.groups()
('12-Mar-2021', '***IDCW Payout @ Rs.4.50000000 per unit  (TDS :453.13, TDS Rate:', '.', None, None, None)

**Comment by codereverser** [comment]
Looks like the 7.50% is not a single word in the pdf. shall fix this today.

**Comment by sathishweb** [comment]
Thank you for the quick responses!

**Comment by codereverser** [comment]
Can you please test the code using 0.4.7 alpha 2 version? 

```
pip install casparser==0.4.7a2
```

**Comment by sathishweb** [comment]
I tested it and it worked fine. I am now able to parse my statement. Thanks a lot.

**Comment by codereverser** [comment]
Nice! Many thanks for testing. 

fixed in https://github.com/codereverser/casparser/commit/0663b5417fb7b6dc9bbe74763dd68047b82b6d25
