### ISSUE TITLE
Incase registrar is kfintech, library is not able to fetch the schemes

### ISSUE THREAD

**Issue by nipungarg59** [codereverser/casparser#34]
<img width="752" alt="Screenshot 2021-06-25 at 10 52 46 PM" src="https://user-images.githubusercontent.com/9325339/123462909-838bed00-d608-11eb-9671-b6a5f8559323.png">

This file contains both kfintech and cams registrar data. It is generated from cams website only.

**Comment by codereverser** [comment]
seems to be related to https://github.com/codereverser/casparser/issues/22 
Can you please send me the exact error? Does the library throw any error?

**Comment by codereverser** [comment]
![image](https://user-images.githubusercontent.com/8553055/123472503-e1becd00-d614-11eb-83e3-0d0c5cf33ac3.png)
![image](https://user-images.githubusercontent.com/8553055/123472560-f26f4300-d614-11eb-9f64-172968a5d33a.png)

It works fine with the sample files I have. 🤔

**Comment by nipungarg59** [comment]
Library does not throw any error, but it does not populate the schemes inside the folio

**Comment by codereverser** [comment]
Can you please let me know the python and the library versions, you are using?

**Comment by nipungarg59** [comment]
I am using python 3.9.4 and casparser==0.4.7

**Comment by codereverser** [comment]
closing as per author's request.
