### ISSUE TITLE
Different exception for when the password is incorrect

### ISSUE THREAD

**Issue by rishabhc32** [codereverser/casparser#39]
In the current code `CASParseError("Incorrect PDF password!")` is raised when the password is wrong. 
https://github.com/codereverser/casparser/blob/e507c5305554df16fcc3d48c709cfd20fe463eb9/casparser/parsers/mupdf.py#L200

So you have to do ugly things like:
```python
try:
    read_cas_pdf("pdf", "password")
except CASParseError as err:
    if err.args:
        if 'incorrect pdf password' in err.args[0].lower():
            raise InvalidPasswordError
    
    raise
```

One possible solution could be to create a separate Exception for wrong password inheriting from `CASParseError`. Or a `code` attribute could be set in the `CASParseError` class, whose value could be like `incorrect_password`(or something else depending on the context where it is raised) which you can check for when handling the exception.

If you don't have the bandwidth, I can make a PR for the same this weekend.

**Comment by codereverser** [comment]
Oh! that makes sense.

I'll add a separate exception for invalid passwords and make a release by this weekend.
