### ISSUE TITLE
Kfintech report parsing always results in error

### ISSUE THREAD

**Issue by mandys** [codereverser/casparser#4]
Hi,

While this is parsing the CAMs report correctly, I have had no luck getting it to parse the Kfintech report.

I generated it from the url you mention in your Readme.

Get the report and I am able to open it fine.

When I run it, 

➜  casparser (main) ✗ casparser karvy2.pdf
Enter PDF password:
Error parsing pdf file :: Error parsing CAS header

Thanks.

**Comment by codereverser** [comment]
Are you running these on detailed karvy statements? 

Not sure what's causing this issue otherwise 😕 ; Also The code is not well tested yet ; it has only been verified against a couple of different portfolios (friends & family) which I could get access to.

**Comment by mandys** [comment]
Yes, I was running these on the detailed ones.

Attaching screenshot of the page from where I generated.

![karvy](https://user-images.githubusercontent.com/31867/99063493-9813fb80-25ca-11eb-8534-f106b6f039b4.png)

What I observed is that last week the report was in a different format.
This week either column spacing or something changed in their report that might have thrown your regex rules.

It looks exactly same, but not while parsing.
Even I tried to parse them.

**Comment by codereverser** [comment]
Hmm. this is weird. For me the pages look like the following. 


**Kfintech** [Link](https://mfs.kfintech.com/investor/General/ConsolidatedAccountStatement)

![image](https://user-images.githubusercontent.com/8553055/99065173-fb9f2880-25cc-11eb-95bc-c2d3fe103194.png)


**CAMS** [Link](https://new.camsonline.com/Investors/Statements/Consolidated-Account-Statement)


![image](https://user-images.githubusercontent.com/8553055/99065422-5f295600-25cd-11eb-8f96-5b872e435019.png)

Also you need to make sure to select `detailed` statement type in each site.

**Comment by codereverser** [comment]
Also tested the code with some more portfolio files yesterday and it seems to be working fine. Just need to make sure to use the above links and select "detailed" statement type. The parser doesn't support "summary" statements (yet..)

**Comment by mandys** [comment]
Yes, it's working with "detailed" and not with "summary" statement.

I guess I used the summary one.

**Comment by codereverser** [comment]
nice! The parser doesn't support summary statements yet. There are plans to add support for those + CAS statements from NSDL/CSDL for demat securities but don't have any estimate as of now. Implementing each of them would need approximately the same amount of effort as of the current version. 

closing this issue for now..
