### ISSUE TITLE
Feature Request: MF category and sub-category

### ISSUE THREAD

**Issue by ajayrawatsap** [codereverser/casparser#41]
HI Team

First of all many thanks for the great package your team has created.

I am author of [repo](https://github.com/ajayrawatsap/mf_data)  and  using your package to  parse the cas pdf for my project.

I have requirement to classify funds based on type debt/equity and subtypes such large cap/small cap etc .

Would it be possible to integrate this feature in your package.

**Comment by codereverser** [comment]
The latest version of the package [v0.5.0](https://pypi.org/project/casparser/0.5.0/) has broad category (`EQUITY` or `DEBT`) classification as part of the capital gains module. 

![image](https://user-images.githubusercontent.com/8553055/126024499-a8b84a36-4f7d-43cf-8b36-5c27c8395dfb.png)

The sub-category classification is planned but may take a while. shall update here once it is implemented.

**Comment by ajayrawatsap** [comment]
Thanks for now it should suffice, closing the issue
