### ISSUE TITLE
Franklin Schemes not Returned

### ISSUE THREAD

**Issue by ajayrawatsap** [codereverser/casparser#42]
Hi Team

The Franklin Mutual Fund house  changed   their registrar to CAMS.
Therefore the data in PDF statement  may have also changed 
The Latest CAS statement is showing the Franklin Schemes but data is not returned by casparser package.

**Comment by codereverser** [comment]
Yeah. this issue is known and the fix is in progress. 

issue: https://github.com/codereverser/casparser-isin/issues/5
fix: https://github.com/codereverser/casparser-isin/pull/6

**Comment by codereverser** [comment]
Can you please post some examples of how the FRANKLIN schemes are reported in the latest statements?

like the following image from an old CAS file
![image](https://user-images.githubusercontent.com/8553055/126187574-dd317eed-0481-4c45-8670-53ae9f8d28c2.png)

**Comment by ajayrawatsap** [comment]
Please find below  screenshots

![FT_schemes](https://user-images.githubusercontent.com/37475177/126192917-e8caf382-ceb0-4400-81a4-464c33ee67bf.png)

let me know if anything else is required.  I can test the fix on all my schemes if you have some temp available which I can download

**Comment by codereverser** [comment]
That would be really helpful. You can test the code by installing the package direct from the repository like 
```
pip install https://github.com/codereverser/casparser-isin/archive/refs/heads/fix/franklin-rta-schemes.zip
```
(not sure if it works with all versions of python, though)

**Comment by ram65875** [comment]
Franklin Templeton created few Segregated Portfolio's for some stressed Mutual Funds. The data is read incorrectly in some cases.  In the example given below - there are 2 Segregation records  - one for qty 215931.176, and second for qty 0.008, but the parser scans the 2nd one as qty 215931.184 ...

{"scheme": "Franklin India Credit Risk Fund- Segregated Portfolio 1 (8.25% Vodafone Idea Ltd-10JUL20-Growth Plan)", 
"advisor": "ICICIRON", 
"rta_code": "FTI880", "type": "DEBT", "rta": "CAMS", "isin": "INF090I01TJ6", "amfi": "147954", "open": "0.000", "close": "0.000", "close_calculated": "215931.176", "valuation": {"date": "2020-07-17", "value": "0.00", "nav": "0.0818"}, 
"transactions": [
{"date": "2020-01-24", "description": "Creation of units - Segregated Portfolio\t\t215,931.176", "amount": "0", "units": "215931.176", "nav": "0", "balance": "215931.176", "type": "SEGREGATION", "dividend_rate": null}, 
{"date": "2020-01-24", "description": "Creation of units - Segregated Portfolio\t\t0.008", "amount": "0", "units": "215931.184", "nav": "0", "balance": "215931.184", "type": "SEGREGATION", "dividend_rate": null}, 
{"date": "2020-06-15", "description": "Payment - Units Extinguished", "amount": "-1338.33", "units": "-16360.996", "nav": "0.0818", "balance": "199570.188", "type": "REDEMPTION", "dividend_rate": null}, 
{"date": "2020-07-10", "description": "Payment - Units Extinguished", "amount": "-16324.84", "units": "-199570.188", "nav": "0.0818", "balance": "0.000", "type": "REDEMPTION", "dividend_rate": null}]}
