### ISSUE TITLE
Issue in Franklin Templeton Segregated Units

### ISSUE THREAD

**Issue by ram65875** [codereverser/casparser#46]
Hello team,

Franklin Templeton created few Segregated Portfolio's for some stressed Mutual Funds. The data is read incorrectly in some cases. In the example given below - there are 2 Segregation records - one for qty 215931.176, and second for qty 0.008, but the parser scans the 2nd one as qty 215931.184 ...

{"scheme": "Franklin India Credit Risk Fund- Segregated Portfolio 1 (8.25% Vodafone Idea Ltd-10JUL20-Growth Plan)",
"advisor": "ICICIRON",
"rta_code": "FTI880", "type": "DEBT", "rta": "CAMS", "isin": "INF090I01TJ6", "amfi": "147954", "open": "0.000", "close": "0.000", "close_calculated": "215931.176", "valuation": {"date": "2020-07-17", "value": "0.00", "nav": "0.0818"},
"transactions": [
{"date": "2020-01-24", "description": "Creation of units - Segregated Portfolio\t\t215,931.176", "amount": "0", "units": "215931.176", "nav": "0", "balance": "215931.176", "type": "SEGREGATION", "dividend_rate": null},
{"date": "2020-01-24", "description": "Creation of units - Segregated Portfolio\t\t0.008", "amount": "0", "units": "215931.184", "nav": "0", "balance": "215931.184", "type": "SEGREGATION", "dividend_rate": null},
{"date": "2020-06-15", "description": "Payment - Units Extinguished", "amount": "-1338.33", "units": "-16360.996", "nav": "0.0818", "balance": "199570.188", "type": "REDEMPTION", "dividend_rate": null},
{"date": "2020-07-10", "description": "Payment - Units Extinguished", "amount": "-16324.84", "units": "-199570.188", "nav": "0.0818", "balance": "0.000", "type": "REDEMPTION", "dividend_rate": null}]}

**Comment by codereverser** [comment]
It looks like the addition of SEGREGATION transaction types doesn't consider multiple incoming transactions in a segregated folio. 

ref: https://github.com/codereverser/casparser/commit/132386ea36438cb87691871fee842d8a83d77183

shall fix this soon. Can you please post a partial screenshot of the transactions for testing the fix?

**Comment by ram65875** [comment]
I suspect the field 'Description' seems to mess up the Qty ...
_"description": "Creation of units - Segregated Portfolio\t\t0.008"_

Have attached the screenshot of actual CAMS statement
<img width="884" alt="Screenshot 2021-07-22 at 10 54 12 AM" src="https://user-images.githubusercontent.com/87629697/126593587-8c115036-0270-43e9-9bdb-bdc6f5088ace.png">

**Comment by codereverser** [comment]
Yes. that's one issue. but there is also this line, that sets wrong units for a segregated transaction

```python
                 units = amt
                 balance = amt
                 amt = 0
                 nav = 0
```

**Comment by codereverser** [comment]
Can you please try testing with the pre-release version `0.5.2b1`?

```pip install casparser==0.5.2b1```

**Comment by ram65875** [comment]
Thanks!! Tested the version and works fine for me!!

**Comment by codereverser** [comment]
Many thanks for testing. 

btw I had a query if you can answer.. How do you calculate capital gains on such a folio? There is no purchase price associated with the payout transactions. Does it need to be matched with the purchase from the original/parent  fund?

**Comment by ram65875** [comment]
I believe the entire thing will have to taken as Capital Gains. And it
should be indexed against the original purchase date.
But, I am no tax expert:)

Regards
Ram
