### ISSUE TITLE
Error while generating capital gains report with Dividend payout scheme

### ISSUE THREAD

**Issue by SudhirSNaik** [codereverser/casparser#48]
Getting the following error

  File "\lib\site-packages\casparser\analysis\gains.py", line 192, in merge_transactions
    merged_transactions[dt].units += txn["units"]
TypeError: unsupported operand type(s) for +=: 'decimal.Decimal' and 'NoneType'

Dividend payout transactions have nothing in the "Units" column as shown in screenshot below (Only "Amount" column)  
![image](https://user-images.githubusercontent.com/73683130/127689118-15bd3dc2-7f3a-4445-94ba-5ea47b3eedef.png)

**Comment by codereverser** [comment]
fix being tested in #47

**Comment by codereverser** [comment]
Can you please try testing with the pre-release version `0.5.2b1`?

```
pip install casparser==0.5.2b1
```

**Comment by SudhirSNaik** [comment]
The issue is resolved and I can see the Capital Gains Statement table being printed on the console

**Comment by codereverser** [comment]
fixed in #7  & v0.5.2 will be released today
