### ISSUE TITLE
Unable to parse investor data

### ISSUE THREAD

**Issue by usharab** [codereverser/casparser#52]
This is the code I am using to get the parsed data
```
import casparser


def main():
    data = casparser.read_cas_pdf('./demo2/JUL2020_AA03773313_TXN.pdf', 'FVXPK2945F', output="json")
    # data = casparser.read_cas_pdf('./demo2/MAR2021_AA06997817_TXN.pdf', password='BCDPJ0121K', force_pdfminer=True)
    print()


if __name__ == '__main__':
    main()

```
and this is what the error is 

```

Traceback (most recent call last):
  File "/home/usharab/.local/lib/python3.8/site-packages/casparser/parser.py", line 163, in read_cas_pdf
    investor_info = parse_investor_info(layout, *page.mediabox[2:])
  File "/home/usharab/.local/lib/python3.8/site-packages/casparser/parser.py", line 55, in parse_investor_info
    raise CASParseError("Unable to parse investor data")
casparser.exceptions.CASParseError: Unable to parse investor data
```

The version of casparser I am using is '0.2.1' and before this version I was using version '0.5.3' and that version gave the same error. Can anyone guide me what could be the issue?

 I have also tried force_pdfminer too and that also returned the same error

**Comment by Kunnuman** [comment]
Just hazarding a guess here - is the PDF file in the usual CAS statement format? I've found the parser works really well consistently on CAS files but obviously would fail if the layout is different.

**Comment by codereverser** [comment]
I'm sorry but CDSL statements are not yet supported by casparser, as it is primarily meant to handle only mutual funds and it does not have enough info to parse other demat transactions. 

Closing this issue for now; I'll update here when CDSL/NDSL statement parsers are added to the module. 

please feel free to re-open if this is not the case.
