### ISSUE TITLE
HeaderParseError: Error parsing CAS header

### ISSUE THREAD

**Issue by rahuliitg** [codereverser/casparser#56]
---------------------------------------------------------------------------
HeaderParseError                          Traceback (most recent call last)
<ipython-input-9-20336b997755> in <module>()
----> 1 json_str = data = casparser.read_cas_pdf("33220217220210621ZFBF290265631DC70CPIMBCP130542292.pdf", "abcd1234")

2 frames
/usr/local/lib/python3.7/dist-packages/casparser/process.py in parse_header(text)
     17     if m:
     18         return m.groupdict()
---> 19     raise HeaderParseError("Error parsing CAS header")
     20 
     21 

HeaderParseError: Error parsing CAS header

Code:
json_str = data = casparser.read_cas_pdf("33220217220210621ZFBF290265631DC70CPIMBCP130542292.pdf", "xyz")

**Comment by codereverser** [comment]
Looks like you are using an older version of the package. Can you please try with a newer python version? latest versions of casparser needs minimum python 3.8

**Comment by codereverser** [comment]
python<3.8 are not supported
