### ISSUE TITLE
We can export exceptions so that user can return specific response instead of generic exception handling

### ISSUE THREAD

**Issue by ashutosh264** [codereverser/casparser#57]
When we try to parse files & anything fails we catch need to catch that exception in a generic way & return a response.
Instead, if we export excpetions.py classes, it will make it easier for users to catch these exceptions.

**Comment by codereverser** [comment]
Sorry, I didn't get you. You can import individual exception classes and handle each error accordingly. 

for eg:- https://github.com/codereverser/casparser-web/blob/69b7e9308a7f1728f924b5f810e36aa6ed852aba/app.py#L122

**Comment by codereverser** [comment]
Closing as the issue description is not clear. Please re-open the issue with more info. 

PRs are welcome too!
