### ISSUE TITLE
having issue in parsing on linux server

### ISSUE THREAD

**Issue by vipuljain28** [codereverser/casparser#61]
There is no formatting in json transaction have no keys and summary also having some missing keys from parsing on local system.

**Comment by codereverser** [comment]
can you please provide more details? The same code is deployed on a linux server @ https://cas.atomcoder.com and it works fine (at least with all files I could test)

**Comment by vipuljain28** [comment]
yes, when I am parsing data on the Linux server it is not extracting pan and arn no., nominee pan and kyc ok.
these fields are in the cas file and these were parsed before. when we are using the old format. Check the screen  shot

![parsed](https://github.com/codereverser/casparser/assets/5869283/60e7c362-17fe-42ef-aefa-16df68f3295d)
![cas](https://github.com/codereverser/casparser/assets/5869283/e32950c6-2849-4440-a443-a574d2ea73e3)

**Comment by codereverser** [comment]
Both these issues (PAN and Advisor ARN) were fixed recently and should be available in v0.7.3 of casparser library (released 2 days back). 

Can you please give it a try?

**Comment by vipuljain28** [comment]
Thank you for the update. Sorry for the delay response. I have checked that and the issue has been fixed.
