### ISSUE TITLE
Unable to fetch amfi values of recently renamed funds.

### ISSUE THREAD

**Issue by basantwanishraddha** [codereverser/casparser#62]
Adding the schemes json snippet for reference : 
            "schemes": [
                {
                    "scheme": "HSBC Medium Duration Fund - Regular Growth (Formerly",
                    "advisor": "N/A",
                    "rta_code": "OLRCBG",
                    "rta": "CAMS",
                    "isin": null,
                    "amfi": null,
                    "type": "N/A",
                    "open": "xxx",
                    "close": "xxx",
                    "valuation": {
                        "date": "2023-01-12",
                        "nav": "16.9027",
                        "value": "2637.70"
                    },
                    "transactions": []
                }

**Comment by codereverser** [comment]
Can you please give it a try after updating the dependent module `casparser-isin` ? I've released a new version, that should have the latest database. 

```
pip install -U casparser-isin
```

**Comment by basantwanishraddha** [comment]
Yeah latest version of casparser-isin was able to resolve the issue. Thanks.
