### ISSUE TITLE
Error! - Cannot compute gains. CAS is incomplete!

### ISSUE THREAD

**Issue by Curiosity007** [codereverser/casparser#66]
Generated file from here 

https://www.camsonline.com/Investors/Statements/Consolidated-Account-Statement

still this error

**Comment by codereverser** [comment]
gains can be computed only if the statement is complete.. i.e. the opening balance of all funds in the statement is zero. 

Can you please try with 01-Jan-1990 as the start date for the statement?

**Comment by codereverser** [comment]
this should be fixed in the latest version v0.7.2
