### ISSUE TITLE
Issue when there is space character inside RTA code #14

### ISSUE THREAD

**Issue by pranav-myfi** [codereverser/casparser#67]
<img width="524" alt="Screenshot 2023-04-03 at 8 32 14 AM" src="https://user-images.githubusercontent.com/129410317/229401793-e4d603e2-d9cb-4c0f-9bda-071688e09f74.png">

The SUMMARY_ROW_RE regex fails when there are RTA codes like the second and third row. It ends up reading folio number along with the first three characters of RTA code resulting in a null repsonse when ISIN check is done.

**Comment by pranav-myfi** [comment]
@codereverser The fix for this is to modify the `SUMMARY_ROW_RE` regex to the below regex:
```
SUMMARY_ROW_RE = (
    r"([\d/\s]+?)(?=\s\d)\s+([\s\w]+)-\s*\d*\s*(.+?)\s*([\d,.]+)\s*"
    r"(\d{2}-[A-Za-z]{3}-\d{4})\s*([\d,.]+)\s*([\d,.]+)\s*(\w+)\s*$"
)
```

I tried making an MR, but couldnt. Can you check this out and verify this fix?

**Comment by codereverser** [comment]
many thanks for the report and fix. Shall verify this and release next version asap.

**Comment by codereverser** [comment]
thanks for the fix. new version released.

**Comment by pranav-myfi** [comment]
Thanks!
