### ISSUE TITLE
Issue in parsing Schemes names without "Advisor"

### ISSUE THREAD

**Issue by SudhirSNaik** [codereverser/casparser#7]
This parser is really helpful.

In my CAMS CAS, there are a few Scheme entries without "Advisor" like below 

![CAMS_CAS](https://user-images.githubusercontent.com/73683130/102732102-ccb06b00-435f-11eb-8314-7a26adde12ed.JPG)

The parser skips those particular  schemes due to "SCHEME_RE" not matching.
Can something be done regarding this?

**Comment by codereverser** [comment]
Thanks for reporting the bug with screenshot. 

I'll upload a fix in a PR. I don't have any sample files with me for testing this myself. Can you please test and let me know if it fixes the issue?

**Comment by SudhirSNaik** [comment]
Yes, Schemes with and without advisor are being parsed now without issues.

Thank you.

**Comment by codereverser** [comment]
Many thanks. shall merge the fix then.
