### ISSUE TITLE
parser not working, resulting in excalamation mark / error rather than checked

### ISSUE THREAD

**Issue by isaac-philip** [codereverser/casparser#78]
I generated a consolidated report from CAS - CAMS + KFintech at https://www.camsonline.com/Investors/Statements/Consolidated-Account-Statement

Executing the casparser cli utility does not return successfully.

Is this expected ?

Please note the Error and the Excalamation marks in the image below.

![casparser_snippet_error](https://github.com/codereverser/casparser/assets/4974658/d8e0b6b8-bf04-4ea7-a60c-5578ec54afc3)

Command executed,

`$ casparser <filename>.pdf -p '<$password$>'`

File Type details,

> File Type : FileType.CAMS                                                                                     
                                                                 CAS Type : CASFileType.DETAILED  

also, is up-to-date,

```
(.venv_py310) iceman@pop-os ~/D/M/Statements> casparser-isin --update
2023-08-31 00:26:23,325 - INFO - Fetching remote isin db metadata
2023-08-31 00:26:24,283 - INFO - Local db version  : 2023.8.18
2023-08-31 00:26:24,283 - INFO - Remote db version : 2023.8.18
2023-08-31 00:26:24,283 - INFO - casparser-isin database is already upto date
```

**Comment by codereverser** [comment]
Thanks for the report. 

Looks like the CAS format has changed recently. Shall push an updated version in a couple of days.

**Comment by isaac-philip** [comment]
cool thanks, plz consider me as a reviewer. 

We could have a test with the new file/format validating the changes if possible?

**Comment by codereverser** [comment]
> cool thanks, plz consider me as a reviewer.
> 
> We could have a test with the new file/format validating the changes if possible?

I've created PR #79 with support for new files. Can you please give it a try?
